FROM python:3.11-slim

WORKDIR /app

# Copy dependency files first (better caching)
COPY pyproject.toml uv.lock ./

# Install uv and dependencies
RUN pip install --no-cache-dir uv \
    && uv sync --frozen

# Copy rest of the app
COPY . .

# Fix imports
ENV PYTHONPATH=/app

# Expose port
EXPOSE 8501

# Run app
CMD ["uv", "run", "streamlit","run", "ui/chat_ui.py", "--server.address=0.0.0.0",  "--server.port=8501"]